name: Quality assurance

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare virtual environment
      run: make configure

    - name: Lint
      run: make lint

    - name: Check package build
      run: make build